trigger:
 - main

pool:
  vmImage: 'ubuntu-latest' 

variables:
  imageName: 'pipelines-javascript-docker'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'hveregistry'
    repository: 'javascriptdocker'
    command: 'buildAndPush'
    Dockerfile: 'app/Dockerfile'
    buildContext: 'app'
